wireguard:
    private: ENC[AES256_GCM,data:PKJ2cpRAMhtcfltW0NJ5L3Pqp45t/RJCqqlDz181cnTbHDQvPNykKY/2FQk=,iv:8EnVVjCxh1O+SToPh3XrqG/GmbJblWckBjGZjAuC9gs=,tag:74ItcPXuVMxfWsdqaCFk9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ngtqmruwk40k2h3r2s8x4rakaeca3ahdmymt7dntyyc2954ucvvs9dkrx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYVBMQ2dqajE2TGhMQTB2
            NzZKaVpvaWNIUW5sK3d5d3FqaWpjYmx3QXhjCml0eVRNVjRDREVNRkNabExBdHQ5
            VmRlUTlMKzdjRlVhZ0VrdjdzNE10SUUKLS0tIFhOUVJ0TWhaNGhMNENqdDNmcDRZ
            OFNHQTlUeFdzTlBqakVRTkh3bzFFQ3MKl0JjEH2mXoD9E0eqSVzNGpqNoef5ELiP
            Z9rB89En28Wx9QgFvz4anNmbUQ1Azri+Q+zKmstBAVRoDqERye5J5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T10:03:58Z"
    mac: ENC[AES256_GCM,data:5MBsgAifBNXgfWqiZFZg364OnLI/K/i7UKY/CtgWf9WhJw/4H5RB1yENkbVu14IQ39GMJWeiKSniVFRBSZqWBVKujhlrYfY+3nSeXHz2VfH7utVk0gO08IkhhPhwLE2XIcm+C6SjptmxOxT9Te9GqxHUfjQDA2KaXm7sl9DH75w=,iv:3hKKE/8o3VdUlLaZTCkZHP63GevttxIZDFATMk6dIbQ=,tag:S99FSYjcztWrO0vPtJTJeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
